name: deploy-shopn-cms

env:
  KUBECONFIG: /home/deploy/config
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -f Dockerfile -t kamilwronka7/shopn-cms .
      - run: docker login -u $DOCKER_ID -p $DOCKER_PASS
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      - run: docker push kamilwronka7/shopn-cms
      - run: sudo mkdir -p /home/deploy
      - run: echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $KUBECONFIG
      - run: kubectl rollout restart deployment shopn-cms-depl
